##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [3]:
import numpy as np 

a = np.array([1,2,3,4])

In [7]:
print(len(a))

print(a.ndim)

4
1


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [10]:
array2 = np.array([[1,2,6,7],
 [4,3,9,5]])

array3 = np.array([[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]])


# dimension 
print(array2.ndim)
print(array3.ndim)

# of elements 
print(array2.size)
print(array3.size)

# row & column info
print(np.shape(array2))
print(np.shape(array3))




2
3
8
12
(2, 4)
(2, 2, 3)


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [11]:
#İki boyutlu arraydaki 2 elemanına ulaşalım

array2[0,1]

2

In [12]:
#İki boyutlu arraydaki 7 elemanına ulaşalım

array2[0, -1]

7

In [13]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım

array3[1,1,-1]

9

In [4]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım

array3[0, 0, 1]

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [15]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım

array2

array2[0, 1:3]

array([2, 6])

In [17]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım

array2

array2[1, 1:]

array([3, 9, 5])

In [21]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım

array3

array3[0, 1, :]

array([21,  8, 11])

In [23]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım

array3

array3[1,0, 1:3]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [31]:
array4 = np.array([0,1,0,0,1,0,1,0,1,0,1,0,1,1,0])
array5 = np.array([1,0,0,0,0,1,1,1,1,0,0,1,0,1,0])

new_array1 = array4.reshape(5,3) 
new_array2 = array5.reshape(5,3)

np.concatenate([new_array1, new_array2])


array([[0, 1, 0],
       [0, 1, 0],
       [1, 0, 1],
       [0, 1, 0],
       [1, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [0, 0, 1],
       [0, 1, 0]])